- id: prose-check
  name: Check prose for AI patterns
  description: Scan documents for LLM-isms and AI writing patterns
  entry: python check_writing.py
  language: python
  types: [markdown, text]
  pass_filenames: true
  require_serial: false
  additional_dependencies:
    - pyyaml>=6.0
    - jinja2>=3.0
